@startmindmap


+ Conceptos clave
++ Tecnologías Emergentes
+++ Big Data
++++ Inteligencia de Negocios (BI)
++++ Machine Learning
++++ Cloud Computing
+++ Blockchain
+++ Inteligencia Artificial (IA)
++++ Machine Learning
+++ Internet of Things (IoT)
++++ Industria 4.0

++ Estrategias de Negocio
+++ Transformación Digital
+++ Océano Azul
+++ Modelo Canvas

++ Gestión y Operaciones
+++ ERP (Enterprise Resource Planning)
+++ CRM (Customer Relationship Management)
+++ Integración de Sistemas de Gestión
+++ ITIL

-- Seguridad y Protección
--- Ciberseguridad
--- Cloud Computing

-- Innovación y Desarrollo
--- Innovación
--- Talento Digital
--- Talento STEM
--- Profesionales STEM

-- Comunicación y Redes
--- Redes Informáticas
---- Modelo TCP/IP
--- NFC
--- Latencia

-- Experiencias Digitales
--- Realidad Aumentada (RA)
--- Realidad Virtual (RV)

-- Métodos de Trabajo
--- Outsourcing
--- Operación de Sistemas
--- SLA (Service Level Agreement)

@endmindmap
