@startmindmap
+ Funciones de la DSI
-- Definición y rol
--+ Importancia estratégica en las organizaciones
--+ Integración de tecnologías avanzadas
-- Evolución histórica
--+ Desde el microprocesador hasta la computación en la nube
--+ Impacto de cada tecnología en la transformación empresarial
-- Recursos materiales
--+ Hardware: Componentes físicos esenciales
--+ Software: Aplicaciones para ejecutar procesos
--+ Redes de comunicación: Infraestructura para la conectividad
++ Gestión del talento
+++ Identificación de habilidades digitales necesarias
+++ Estructura de roles desde operativos hasta estratégicos
++ Componentes organizacionales
+++ Diferenciación entre niveles estratégicos y técnicos
+++ Categorías profesionales en TIC y sus funciones específicas
++ Actividades principales
+++ Desarrollo y mantenimiento de sistemas
+++ Supervisión de la seguridad y la integridad de datos
++ Objetivos
+++ Alineación con la estrategia empresarial global
+++ Adaptabilidad y respuesta ante el cambio tecnológico
@endmindmap
