package Empresa {

Empresav001 ...r...> Empresav002 : pasa el tiempo\ncambia el ecosistema\n\n\n

Empresav001 <-d- Estrategiav001
Estrategiav001 -d- Planificacionv001

Empresav002 <-d- Estrategiav002
Estrategiav002 -d- Planificacionv002

Estrategiav001 -r- Innovación
Innovación -r- Estrategiav002

}
